# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDanoshopreview():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_danoshopreview(self):
    self.driver.get("https://qa.danoshop.net/product?product_no=511")
    time.sleep(2)
    self.driver.set_window_size(1000, 800)
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".the-number-of-reviews").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-o75ts-FilterOption").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-o75ts-FilterOption").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "check-btn").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-1ipia16:nth-child(1) .css-16oridp").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-n59f5a > svg").click()
    time.sleep(2)
    self.driver.close()
    time.sleep(2)
  
