# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDanoshopquestion():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_danoshopquestion(self):
    self.driver.get("https://qa.danoshop.net/product?product_no=511")
    time.sleep(2)
    self.driver.set_window_size(1000, 800)
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".menu-item:nth-child(4)").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "상품Q&A쓰기").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "member_id").send_keys("onlydano_test45")
    time.sleep(2)
    self.driver.find_element(By.ID, "member_passwd").send_keys("qwe321")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".loginok").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "title").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "title").send_keys("테스트")
    time.sleep(2)
    self.driver.find_element(By.ID, "textArea").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "textArea").send_keys("테스트")
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "등록").click()
    time.sleep(4)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) .product_name").click()
    time.sleep(2)
    self.driver.close()
    time.sleep(2)
    
  
