# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDanoshoppayment2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_danoshoppayment2(self):
    self.driver.get("https://qa.danoshop.net/product?product_no=327")
    time.sleep(2)
    self.driver.set_window_size(1000, 800)
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-1yb80zs").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "member_id").send_keys("onlydano_test2")
    time.sleep(2)
    self.driver.find_element(By.ID, "member_passwd").send_keys("qwe321")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".loginok").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-1qd07mv-StyledDropdown:nth-child(1)").click()
    time.sleep(2)
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".css-1qd07mv-StyledDropdown:nth-child(1)")
    time.sleep(4)
    dropdown.find_element(By.XPATH, "//option[. = '다노 홈트매트 [20% 할인] 78,400원']").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-17zrffq-Button").click()
    time.sleep(2)
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-17zrffq-Button")
    time.sleep(2)
    actions = ActionChains(self.driver)
    time.sleep(2)
    actions.move_to_element(element).perform()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-1jn0ey1-OrderBtn > span").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "shippingMemo").click()
    time.sleep(2)
    dropdown = self.driver.find_element(By.NAME, "shippingMemo")
    time.sleep(2)
    dropdown.find_element(By.XPATH, "//option[. = '직접 받고 부재 시 문앞에 놓아주세요']").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-1otnxxr-StyledButton:nth-child(2) > button").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-1otnxxr-StyledButton:nth-child(3) > button").click()
    time.sleep(2)
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-1otnxxr-StyledButton:nth-child(3) > button")
    time.sleep(2)
    actions = ActionChains(self.driver)
    time.sleep(2)
    actions.move_to_element(element).perform()
    time.sleep(2)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    time.sleep(2)
    #actions = ActionChains(self.driver)
    #time.sleep(2)
    #actions.move_to_element(element, 0, 0).perform()
    #time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-ru7pth-StyledPaymentMethod:nth-child(7)").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "confirmbox1").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "confirmbox3").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-3p79os-OrderButton").click()
    time.sleep(2)
    self.driver.close()
    time.sleep(2)
  
