# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDanoshopsearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_danoshopsearch(self):
    self.driver.get("https://qa.danoshop.net/pan?key=chungeuiyong")
    self.driver.set_window_size(1000, 800)
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "#header-left svg").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "search").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "search").send_keys("다노닭")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".search-icon-wrapper > img").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".prd-list:nth-child(1) .c-dfvhLe").click()
    time.sleep(2)
  
