# Generated by Selenium IDE
from socket import timeout
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDanofitpayment():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    options.add_experimental_option("excludeSwitches", ["enable-logging"])
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_danofitpayment(self):
    timeout = 500
    self.driver.get("https://danofit-stand-stage.internal.dano.me/danofit")
    timeout = 500
    time.sleep(1)
    self.driver.set_window_size(1000, 800)
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui-gYqUNx-size-xlarge > .c-cHZnbS").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "member_id").send_keys("") #신규 계정정보 생성후 기입 필요 (무료체험x)
    time.sleep(2)
    self.driver.find_element(By.ID, "member_passwd").send_keys("qwe321")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".loginok").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui-gYqUNx-size-xlarge").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "input-1").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "input-1").send_keys("")
    time.sleep(2)
    self.driver.find_element(By.ID, "input-2").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "input-2").send_keys("")
    time.sleep(2)
    self.driver.find_element(By.ID, "input-3").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "input-3").send_keys("")
    time.sleep(2)
    self.driver.find_element(By.ID, "input-4").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "input-4").send_keys("")
    time.sleep(2)
    self.driver.find_element(By.ID, "input-5").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "input-5").send_keys("")
    time.sleep(2)
    self.driver.find_element(By.ID, "input-6").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "input-6").send_keys("")
    time.sleep(2)
    self.driver.find_element(By.ID, "input-7").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "input-7").send_keys("")
    time.sleep(2)
    self.driver.find_element(By.ID, "input-8").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "input-8").send_keys("")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-fJDYRu").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui").click()
    time.sleep(2)
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(2)
    self.driver.close()
  
