# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDanoshopcart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_danoshopcart(self):
    self.driver.get("https://qa.danoshop.net/pan?key=chungeuiyong")
    time.sleep(2)
    self.driver.set_window_size(1000, 800)
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-PJLV:nth-child(2) .c-bLEgqE:nth-child(1) .c-idUfoM").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "checkbox_0").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".basket-btn").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-jIkPfS").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".npay_logo").click()
    time.sleep(2)
    self.driver.close()
    time.sleep(2)
  
