# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Testdanofitappdawn():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_danofitappdawn(self):
    self.driver.get("https://danofit-stand-stage.internal.dano.me/")
    self.driver.set_window_size(1000, 800)
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui-gYqUNx-size-xlarge > .c-cHZnbS").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".c-XUuOx-eFfinf-mt-24 .c-cHZnbS").click()
    time.sleep(1)
    self.driver.close()
  
