# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDanoshopaddress():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_danoshopaddress(self):
    self.driver.get("https://qa.danoshop.net/mypage")
    time.sleep(2)
    self.driver.set_window_size(1000, 800)
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bdHSrw-eHmeGy-color-coral").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "member_id").send_keys("onlydano_test45")
    time.sleep(2)
    self.driver.find_element(By.ID, "member_passwd").send_keys("qwe321")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".loginok").click()
    time.sleep(4)
    self.driver.find_element(By.CSS_SELECTOR, ".css-yo92me:nth-child(8) svg").click()
    time.sleep(2)
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-5gs6kp > .text").click()
    time.sleep(2)
    #self.driver.find_element(By.CSS_SELECTOR, ".addr-wrapper:nth-child(2) .btn-wrapper > .btn").click()
    #time.sleep(4)
    #self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm").click()
    #time.sleep(4)
    self.driver.find_element(By.CSS_SELECTOR, ".reg-btn").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "name").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "name").send_keys("정테스터")
    time.sleep(2)
    self.driver.find_element(By.NAME, "phone").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "phone").send_keys("20257870")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".css-1f2hmam-StyledButton-StyledFindAdressButton").click() 
    time.sleep(2)
    #test = self.driver.find_element_by_xpath('//*[@id="searchForm"]/fieldset/div/div')
    #print(test)
    self.driver.find_elements_by_xpath('//*[@id="region_name"]').click()
    time.sleep(2)
    self.driver.find_element_by_xpath('//*[@id="region_name"]').send_keys("토정로 271")
    time.sleep(2)
    self.driver.find_element_by_xpath('//*[@id="searchForm"]/fieldset/div/button[2]').click()
    time.sleep(2)
    #self.driver.switch_to.frame()
    #time.sleep(2)
    #self.driver.switch_to.frame(0)
    #time.sleep(2)
    #self.driver.find_element(By.ID, "region_name").click()
    #time.sleep(2)
    #self.driver.find_element(By.ID, "region_name").send_keys("토정로 271")
    #time.sleep(2)
    #self.driver.find_element(By.NAME, "zipCode").send_keys("04159")
    #time.sleep(2)
    #self.driver.find_element(By.NAME,"address").send_keys("서울 마포구 토정로 271")
    #time.sleep(2)
    #self.driver.find_element(By.CSS_SELECTOR, ".btn_search").click()
    #time.sleep(2)
    #self.driver.find_element(By.CSS_SELECTOR, ".over").click()
    #time.sleep(2)
    #self.driver.switch_to.default_content()
    #time.sleep(2)
    #self.driver.switch_to.default_content()
    #time.sleep(2)
    #self.driver.execute_script("window.scrollTo(0,0)")
    #time.sleep(2)
    self.driver.find_element(By.NAME, "addressDetail").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "addressDetail").send_keys("123")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "#root > div").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    time.sleep(2)
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm").click()
    time.sleep(2)
    self.driver.close()
    time.sleep(2)
  
