# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDanofitnotice():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_danofitnotice(self):
    self.driver.get("https://danofit-stand-stage.internal.dano.me/notice")
    time.sleep(1)
    self.driver.set_window_size(800, 1000)
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".c-giYTwi").click()
    time.sleep(1)
    self.vars["window_handles"] = self.driver.window_handles
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".c-giYTwi").click()
    time.sleep(1)
    self.vars["win6200"] = self.wait_for_window(2000)
    time.sleep(1)
    self.vars["root"] = self.driver.current_window_handle
    time.sleep(1)
    self.driver.switch_to.window(self.vars["win6200"])
    time.sleep(1)
    self.driver.close()
    time.sleep(1)
    self.driver.switch_to.window(self.vars["root"])
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".c-XUuOx > svg").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".c-PJLV-keRLOw-variant-paragraph2").click()
    time.sleep(1)
    self.vars["window_handles"] = self.driver.window_handles
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".c-giYTwi").click()
    time.sleep(1)
    self.vars["win5021"] = self.wait_for_window(2000)
    time.sleep(1)
    self.driver.switch_to.window(self.vars["win5021"])
    time.sleep(1)
    self.driver.close()
    time.sleep(1)
    self.driver.switch_to.window(self.vars["root"])
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".c-XUuOx > svg").click()
    time.sleep(1)
    self.driver.close()
  
