# Generated by Selenium IDE
from socket import timeout
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDanofitlogin():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    options.add_experimental_option("excludeSwitches", ["enable-logging"])
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_danofitlogin(self):
    timeout = 500
    self.driver.get("https://danofit-stand-stage.internal.dano.me/")
    timeout = 500
    time.sleep(1)
    self.driver.set_window_size(1000, 800)
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui-hbYmJA-size-xsmall > .c-cHZnbS").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "member_id").send_keys("danofit_test2")
    time.sleep(1)
    self.driver.find_element(By.ID, "member_passwd").send_keys("qwe321")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".body-container").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".loginok").click()
    time.sleep(1)
    self.driver.close()
  
