# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDanofitcoachpayment():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    options.add_experimental_option("excludeSwitches", ["enable-logging"])
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_danofitcoachpayment(self):
    timeout = 500
    self.driver.get("https://danofit-stand-stage.internal.dano.me/coach")
    timeout = 500
    time.sleep(1)
    self.driver.set_window_size(1000, 800)
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui-hbYmJA-size-xsmall > .c-cHZnbS").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "member_id").send_keys("") #신규 계정정보 생성후 기입 필요 
    time.sleep(2)
    self.driver.find_element(By.ID, "member_passwd").send_keys("qwe321")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".loginok").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui-gYqUNx-size-xlarge > .c-cHZnbS").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-XUuOx:nth-child(1) > .c-cHZnbS > .c-XUuOx").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui-fGHEql-fullWidth-true:nth-child(2)").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-XUuOx:nth-child(1) > .c-cHZnbS > .c-XUuOx > .c-XUuOx").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui-fGHEql-fullWidth-true:nth-child(2)").click()
    time.sleep(2)
    self.vars["window_handles"] = self.driver.window_handles
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-byXnTU > .c-bPFrui-jfvrRO-cv > .c-cHZnbS").click()
    time.sleep(2)
    self.vars["win8144"] = self.wait_for_window(2000)
    time.sleep(2)
    self.vars["root"] = self.driver.current_window_handle
    time.sleep(2)
    self.driver.switch_to.window(self.vars["win8144"])
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-XUuOx:nth-child(3) > .c-cHZnbS").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui-fGHEql-fullWidth-true").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-XUuOx-dPMvsw-bgColor-white:nth-child(1) > .c-cHZnbS").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui-jfvrRO-cv").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-XUuOx:nth-child(1) > .c-bQzyIt > .c-XUuOx:nth-child(1)").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-XUuOx:nth-child(1) > .c-bQzyIt > .c-XUuOx:nth-child(2)").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui-jfvrRO-cv").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-XUuOx:nth-child(2) > .c-XUuOx > .c-XUuOx > .c-XUuOx:nth-child(1) > .c-XUuOx:nth-child(1)").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-gLFDrJ:nth-child(1)").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui-dfWiW-size-large:nth-child(1)").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-XUuOx-eFfinf-mt-24").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-dMpErt").click()
    time.sleep(2)
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".c-dMpErt")
    time.sleep(2)
    dropdown.find_element(By.XPATH, "//option[. = '6개월']").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-cHZnbS").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-XUuOx-eFfinf-mt-24 > .c-XUuOx").click()
    time.sleep(2)
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-fJDYRu").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bPFrui-hRjnvA-cv").click()
    time.sleep(2)
    self.driver.close()
    time.sleep(2)
    self.driver.switch_to.window(self.vars["root"])
    time.sleep(2)
    self.driver.close()
    time.sleep(2)
  
