# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://qa.danoshop.net/mypage")
    time.sleep(2)
    self.driver.set_window_size(1000, 800)
    time.sleep(2)
    element = self.driver.find_element(By.CSS_SELECTOR, "svg:nth-child(2)")
    time.sleep(2)
    actions = ActionChains(self.driver)
    time.sleep(2)
    actions.move_to_element(element).perform()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".c-bdHSrw-eHmeGy-color-coral").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "member_id").send_keys("onlydano_test45")
    time.sleep(2)
    self.driver.find_element(By.ID, "member_passwd").send_keys("qwe321")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".loginok").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .css-15jrqqw:nth-child(2)").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "filter").click()
    time.sleep(2)
    dropdown = self.driver.find_element(By.ID, "filter")
    time.sleep(2)
    dropdown.find_element(By.XPATH, "//option[. = '적립 내역']").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "filter").click()
    time.sleep(2)
    dropdown = self.driver.find_element(By.ID, "filter")
    time.sleep(2)
    dropdown.find_element(By.XPATH, "//option[. = '사용 내역']").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "filter").click()
    time.sleep(2)
    dropdown = self.driver.find_element(By.ID, "filter")
    time.sleep(2)
    dropdown.find_element(By.XPATH, "//option[. = '전체 내역']").click()
    time.sleep(2)
    self.driver.close()
    time.sleep(2)
  
