# Generated by Selenium IDE
import pytest_timeout
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPost1():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    options.add_experimental_option("excludeSwitches", ["enable-logging"])
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  
  def test_post1(self):
    time.sleep(1)
    self.driver.get("https://magazine-stage.dev.seoul.kube.dano.me/")
    timeout = 500
    time.sleep(2)
    self.driver.set_window_size(1000, 800)
    time.sleep(1)
    self.driver.execute_script("window.scrollTo(0,300)")
    time.sleep(1)
    self.driver.find_element(By.ID, "radix-id-0-1-tab-3").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .sxsjo8x .sxw2o1q").click()
    time.sleep(1)
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".sx1z9vs:nth-child(1) > svg").click()
    time.sleep(1)
    self.driver.close()
  
