# Generated by Selenium IDE
from socket import timeout
import pytest_timeout
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Testsearch1():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    options.add_experimental_option("excludeSwitches", ["enable-logging"])
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
    #browser = webdriver.Chrome(options=options)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsearch1(self):
    time.sleep(1)
    self.driver.get("https://magazine-stage.dev.seoul.kube.dano.me/")
    timeout = 300
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".sx93z2f").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".sx3lde5:nth-child(1)").click()
    time.sleep(1)
    self.driver.close()
  
