# Generated by Selenium IDE
import importlib
from socket import timeout


import pytest_timeout
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMain():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    options.add_experimental_option("excludeSwitches", ["enable-logging"])
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mainpy(self):
    time.sleep(1)
    self.driver.get("https://magazine-stage.dev.seoul.kube.dano.me/")
    timeout = 300
    time.sleep(2)
    self.driver.close()
  
